openapi: 3.1.0
info:
  title: SurveySays API
  version: '1.0'
servers:
  - url: https://surveysays-425506.appspot.com  # Replace with your actual base URL
    description: Production server
paths:
  /clean_and_code_survey_data:
    post:
      operationId: cleanAndCodeSurveyData
      summary: Analyze and code survey data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: array
                  items:
                    type: object
                    properties:
                      response:
                        type: string
                n_clusters:
                  type: integer
      responses:
        '200':
          description: Successfully analyzed and coded data
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    response:
                      type: string
                    theme:
                      type: integer
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
